name: Foundry CI
on: push
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v26
      - uses: actions/checkout@v4
      - run: nix --version
      - run: nix flake check
      - run: nix build
